#
# Basic settings.
#
url: http://apophis.cz
title: Honza Malina (Horáček)
description: Osobní web
avatar: /assets/img/avatar.jpg
favicon: data:,
language: cs
author: Jan Malina (Horáček)
keywords: Jan,Malina,Horáček,web,osobní
robots: index,follow

#
# Icons
#
icons:
  rss: false
  email: me@apophis.cz
  github: malinajan
  bitbucket:
  twitter:
  facebook: horacek.jan
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Gems.
#
plugins:
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages", ".htaccess"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
  - Makefile
